name: GitHub Snake

on:
  schedule:
    - cron: '0 0 * * *' # daily at midnight UTC
  workflow_dispatch: # manual run

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Generate GitHub Snake
        uses: Platane/snk@v3
        with:
          github_user_name: LucNIK
          outputs: |
            # Light mode
            dist/github-snake-light.svg?color_snake=#0077FF&color_dots=#EBEDF0,#B3E5FC,#4FC3F7,#0288D1,#01579B&color_background=#FFFFFF
            # Dark mode
            dist/github-snake-dark.svg?color_snake=#00E5FF&color_dots=#161B22,#003B46,#00708A,#00A8C6,#00E5FF&color_background=#0D1117

      - name: Commit updated Snake
        run: |
          git config --local user.name "GitHub Actions"
          git config --local user.email "actions@github.com"
          git add dist/*
          git commit -m "Update GitHub Snake" || echo "No changes to commit"
          git push
